### ISSUE TITLE
jinja appending not working as expected when variable defined outside for loop

### ISSUE THREAD

**Issue by cepitacio** [NikolaLohinski/terraform-provider-jinja#7] opened 2023-03-16 00:37 UTC
As the title highlight appending to variables set outside the for loop is not working as expected.

yaml file content:
```
items:
  - name: test-string
    example: 1
  - name: test-string2
    example: 2
```

Jinja code:
```
{%- set result = [] -%}
{%- for item in items -%}
    {%- set string = item.name ~ ' ' ~ item.example -%} 
    {%- set result = result | append([string]) -%}
{% endfor %}
{{ result }}
```

Above code gives: []

expected result: ['test-string 1', 'test-string2 2']

**Comment by NikolaLohinski** [comment] 2023-03-16 08:05
Hi @Cesar-EF and thank you for your input.

This is the expected behavior, and has actually nothing to do with the filter itself.

When you do `set` assignments within a `{% for ... %}` loop, or any closure such as `{% with ... %} ... {% endwith %}`,  you can not make changes to variables defined outside the closure.

To be able to do that, you have to rely on a Jinja `namespace` as such:
```
{%- set ns = namespace(result=[]) -%}
{%- for item in items -%}
    {%- set value = item.name ~ ' ' ~ item.example -%} 
    {%- set ns.result = ns.result | append(value) -%}
{% endfor %}
{{ ns.result }}
```
Do note that `append` expects an element, not an array. If you want to concatenate arrays, the `concat` filter is there for you.

If that seems like a good enough answer to you, feel free to close the issue and if you feel like it, leave me :star: :pray:

**Comment by cepitacio** [comment] 2023-03-23 21:33
Hi @NikolaLohinski,

That worked. Thanks for the quick reply and solution. 
Now I am facing two other issues:
- Using a variable (var.data) that previously loaded the yaml file fails (see Error 1). 
- The yaml file does not have a primary key that we can depend on like in your examples. How do I tell Jinja to loop through the yaml file if there is no master key present. So it should loop through all the keys like item1 and item2 instead.  

Example of yaml file.

```
---
item1:
  - name: test-string
    example: 1
  - name: test-string2
    example: 2
item2:
  - name: test-string3
    example: 3
  - name: test-string4
    example: 4
```
Jinja template
```
%- set ns = namespace(result=[]) -%}
{%- for item in what-variable-to-use %} ### here is where i want to tell jinja to loop through all the keys like in python data.keys()
  {{ item }}
{% endfor %}
{{ ns.result }}
```

Terraform code:
```
data "jinja_template" "render" {
  template = "template.j2"
  context {

    type = "yaml"
    data = var.data
  }
  strict_undefined = false

}
```

Error 1:

```
var.data is object with 2 attributes
│ 
│ Inappropriate value for attribute "data": string required.
```

**Comment by NikolaLohinski** [comment] 2023-03-24 12:06
Your welcom @Cesar-EF , happy to help !

```
data "jinja_template" "render" {
  template = "template.j2"
  context {

    type = "yaml"
    data = var.data
  }
  strict_undefined = false

}
```
does not work because data is not a string. If it's a terraform object, then you need to `yamlencode(var.data)` it. 

Regarding your second problem, you can easily wrap the input in terraform under an object to iterate on:

```
data "jinja_template" "render" {
  template = "template.j2"
  context {

    type = "yaml"
    data = yamlencode({ root = var.data })
  }
  strict_undefined = false

}
```
and then do:
```
%- set ns = namespace(result=[]) -%}
{%- for item in root %} 
  {{ item }}
{% endfor %}
{{ ns.result }}
```

**Comment by cepitacio** [comment] 2023-03-28 23:17
Thanks again for the great help. This works perfectly. Now I am trying to validate the yaml encoded data against json schema. However, since I have two variables defined as below I am unable to validate the `root` variable that holds the yaml. 

If the data includes just the raw yaml, then it validates fine. 

Example:

```
data "jinja_template" "render" {
  template = "template.j2"
  context {

    type = "yaml"
    data = yamlencode({ 
      root = var.data 
      name = var.name
    })
  }
   validation = {
    "schema" = "schema.json"
}
```

**Comment by NikolaLohinski** [comment] 2023-03-29 20:35
You're welcome.

You can either change your existing schema by nesting it within the JSON file or nest it directly in terraform
```
validation = {
    "schema" = jsonencode({
       type = "object"
       required = ["root"]
       properties = {
           root = jsondecode(file("schema.json"))
       }
    })
}
```

**Comment by NikolaLohinski** [comment] 2023-04-25 14:53
Closing as it seems to me it's all good now

**Closed as completed by NikolaLohinski** 2023-04-25 14:53 UTC

**Comment by cepitacio** [comment] 2023-04-25 14:59
Yes, thank you for all the help and the awesome work! 
⭐️ deserved! :)
